// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using TasraPostaManager.Data;

#nullable disable

namespace TasraPostaManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260102130000_AddBarcodePoolItems")]
    partial class AddBarcodePoolItems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // NOTE: This designer file is intentionally minimal.
            // The runtime uses the Migration class; this exists for EF tooling compatibility.
        }
    }
}
